// PDF export for the Research Notes report. jsPDF is lazy-loaded on first use
// so it lives in its own chunk and never weighs down the main bundle.

export interface PdfNote {
  symbol: string;
  company?: string;
  priceLine?: string; // e.g. "$295.63 · +1.39%"
  text: string;
  updatedAt: number;
}

const MARGIN = 56; // 56pt ≈ 0.78in
const LINE = 15;

export async function downloadNotesPdf(notes: PdfNote[]) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const textW = pageW - MARGIN * 2;
  let y = MARGIN;

  const ensure = (space: number) => {
    if (y + space > pageH - MARGIN) { doc.addPage(); y = MARGIN; }
  };
  const wrapped = (s: string, size: number) => {
    doc.setFontSize(size);
    return doc.splitTextToSize(s, textW) as string[];
  };

  // ── Title block ──
  doc.setFont('helvetica', 'bold').setFontSize(18).setTextColor(20);
  doc.text('AlphaNote — Research Notes', MARGIN, y);
  y += 20;
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(110);
  doc.text(`Exported ${new Date().toLocaleString()}`, MARGIN, y);
  y += 10;
  doc.setDrawColor(200);
  doc.line(MARGIN, y, pageW - MARGIN, y);
  y += 24;

  if (!notes.length) {
    doc.setFont('helvetica', 'italic').setFontSize(11).setTextColor(110);
    doc.text('No notes yet.', MARGIN, y);
    y += LINE;
  }

  for (const n of notes) {
    // Keep the heading and at least two body lines together.
    ensure(70);

    doc.setFont('helvetica', 'bold').setFontSize(13).setTextColor(20);
    doc.text(n.priceLine ? `${n.symbol} — ${n.priceLine}` : n.symbol, MARGIN, y);
    y += 16;

    if (n.company) {
      doc.setFont('helvetica', 'italic').setFontSize(10).setTextColor(110);
      doc.text(n.company, MARGIN, y);
      y += 14;
    }

    doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(40);
    for (const para of n.text.split('\n')) {
      if (!para.trim()) { y += 6; continue; }
      for (const line of wrapped(para, 11)) {
        ensure(LINE);
        doc.text(line, MARGIN, y);
        y += LINE;
      }
    }

    y += 6;
    ensure(14);
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(140);
    doc.text(`Updated ${new Date(n.updatedAt).toLocaleString()}`, MARGIN, y);
    y += 12;
    ensure(10);
    doc.setDrawColor(225);
    doc.line(MARGIN, y, pageW - MARGIN, y);
    y += 22;
  }

  // ── Footer on every page: disclaimer + page number ──
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(150);
    doc.text('Generated by AlphaNote · not financial advice', MARGIN, pageH - 30);
    doc.text(`${i} / ${pages}`, pageW - MARGIN, pageH - 30, { align: 'right' });
  }

  doc.save(`alphanote-research-${new Date().toISOString().slice(0, 10)}.pdf`);
}
