import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { getJSON } from '../lib/api';
import type { MoverItem } from '../lib/models';
import Card from '../components/Card';
import { toast } from '../components/toast';
import { getNotes, saveNote, deleteNote, onStorageChange, type Note } from '../lib/storage';
import { formatPrice, formatPct } from '../lib/format';

export default function Notes() {
  const [params] = useSearchParams();
  const focusSymbol = (params.get('symbol') || '').toUpperCase().trim();

  const [notes, setNotes] = useState<Record<string, Note>>(getNotes());
  const [quotes, setQuotes] = useState<Record<string, MoverItem>>({});
  const [draftSym, setDraftSym] = useState(focusSymbol);
  const [draftText, setDraftText] = useState('');
  const [showExport, setShowExport] = useState(false);

  useEffect(() => onStorageChange(() => setNotes(getNotes())), []);

  // Enrich noted symbols with live quotes for the report.
  const symbolList = useMemo(() => Object.keys(notes), [notes]);
  useEffect(() => {
    if (!symbolList.length) { setQuotes({}); return; }
    getJSON<{ items: MoverItem[] }>(`/api/watchlist?symbols=${encodeURIComponent(symbolList.join(','))}`)
      .then((d) => setQuotes(Object.fromEntries(d.items.map((i) => [i.symbol, i]))))
      .catch(() => {});
  }, [symbolList.join(',')]);

  const ordered = useMemo(() => Object.values(notes).sort((a, b) => b.updatedAt - a.updatedAt), [notes]);

  const addDraft = () => {
    const s = draftSym.trim().toUpperCase();
    if (!s || !draftText.trim()) { toast('Add a symbol and some text'); return; }
    saveNote(s, draftText.trim());
    setDraftText(''); setDraftSym('');
    toast(`Note saved for ${s}`);
  };

  const markdown = useMemo(() => {
    const lines = ['# AlphaNote — Research Notes', '', `_Exported ${new Date().toLocaleString()}_`, ''];
    if (!ordered.length) lines.push('_No notes yet._');
    for (const n of ordered) {
      const q = quotes[n.symbol];
      const head = q ? `## ${n.symbol} — ${formatPrice(q.price, q.currency)} (${formatPct(q.changePercent)})` : `## ${n.symbol}`;
      lines.push(head, '');
      if (q?.name) lines.push(`*${q.name}*`, '');
      n.text.split('\n').forEach((l) => lines.push(l));
      lines.push('', `<sub>Updated ${new Date(n.updatedAt).toLocaleString()}</sub>`, '', '---', '');
    }
    lines.push('', '_Generated by AlphaNote. Not financial advice._');
    return lines.join('\n');
  }, [ordered, quotes]);

  const download = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `alphanote-research-${new Date().toISOString().slice(0, 10)}.md`;
    a.click(); URL.revokeObjectURL(url);
    toast('Report downloaded');
  };
  const copy = () => { navigator.clipboard.writeText(markdown).then(() => toast('Markdown copied')); };

  return (
    <div>
      <div className="page-head" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
        <div>
          <h1>Research Notes</h1>
          <p>Jot a thesis per ticker, then export a Markdown research report.</p>
        </div>
        <div className="row">
          <button className="btn" onClick={() => setShowExport((s) => !s)}>{showExport ? 'Hide report' : '⤓ Export report'}</button>
        </div>
      </div>

      {showExport && (
        <Card title="Markdown report" sub={`${ordered.length} note${ordered.length === 1 ? '' : 's'}`} style={{ marginBottom: 16 }}
          right={<div className="row"><button className="btn sm" onClick={copy}>Copy</button><button className="btn sm primary" onClick={download}>Download .md</button></div>}>
          <div className="md-preview">{markdown}</div>
        </Card>
      )}

      {/* Composer */}
      <Card title="New note" style={{ marginBottom: 16 }}>
        <div className="row" style={{ marginBottom: 10 }}>
          <input className="searchbar" style={{ flex: '0 0 140px', height: 38, padding: '0 12px', borderRadius: 10, background: 'var(--color-bg-base)', border: '1px solid var(--color-border)', color: 'inherit' }}
            placeholder="Symbol" value={draftSym} onChange={(e) => setDraftSym(e.target.value.toUpperCase())} />
          <div style={{ flex: 1, minWidth: 220 }} />
        </div>
        <textarea className="note-textarea" placeholder="Your thesis, catalysts, valuation read, risks…" value={draftText} onChange={(e) => setDraftText(e.target.value)} />
        <div style={{ marginTop: 10 }}><button className="btn primary" onClick={addDraft}>Save note</button></div>
      </Card>

      {/* Existing notes */}
      {ordered.length === 0 ? (
        <div className="empty"><strong>No research notes yet</strong>Add one above, or open an asset and hit “Add note”.</div>
      ) : (
        <Card title="All notes">
          {ordered.map((n) => (
            <NoteEditor key={n.symbol} note={n} quote={quotes[n.symbol]} />
          ))}
        </Card>
      )}
    </div>
  );
}

function NoteEditor({ note, quote }: { note: Note; quote?: MoverItem }) {
  const [text, setText] = useState(note.text);
  useEffect(() => setText(note.text), [note.text, note.updatedAt]);
  const dirty = text !== note.text;
  return (
    <div className="note-row">
      <div className="sym">
        <Link to={`/explorer?symbol=${encodeURIComponent(note.symbol)}`} style={{ color: 'var(--color-accent)' }}>{note.symbol}</Link>
        {quote && <div style={{ fontSize: 12, color: 'var(--color-text-muted)', fontWeight: 400 }}>{formatPrice(quote.price, quote.currency)} · {formatPct(quote.changePercent)}</div>}
      </div>
      <div style={{ flex: 1 }}>
        <textarea className="note-textarea" value={text} onChange={(e) => setText(e.target.value)} />
        <div className="row" style={{ marginTop: 8 }}>
          <button className="btn sm primary" disabled={!dirty} onClick={() => { saveNote(note.symbol, text); toast(`Saved ${note.symbol}`); }}>Save</button>
          <button className="btn sm danger" onClick={() => { deleteNote(note.symbol); toast(`Deleted ${note.symbol}`); }}>Delete</button>
        </div>
      </div>
    </div>
  );
}
